### ISSUE TITLE
Revisit global disabling of SELinux on CentOS

### ISSUE THREAD

**Issue by aknot242** [nginxinc/ansible-role-nginx-app-protect#3]
Need to remove the [global disabling of SELinux on CentOS](https://github.com/nginxinc/ansible-role-nginx-app-protect/blob/c0597cbe3ff95120dee2bdf313a49d2fff19e2f0/tasks/prerequisites/setup-centos.yml#L7) (and RHEL, future) for security reasons. Need to take a more surgical approach based on a couple of resources:

https://www.nginx.com/blog/using-nginx-plus-with-selinux/?_ga=2.151629625.1669196458.1589810351-710787638.1580222492

https://wiki.centos.org/HowTos/SELinux

**Comment by magicalyak** [comment]
You can assign this to me.

**Comment by aknot242** [comment]
NGINX App Protect 1.3 now handles selinux policy at installation time. CLosing.
