### ISSUE TITLE
nginx_app_protect_license is undefined

### ISSUE THREAD

**Issue by nergalex** [nginxinc/ansible-role-nginx-app-protect#41]
**Describe the bug**
Get error:
```
TASK [nginx_app_protect : Copy NGINX App Protect certificate and license key] ***
fatal: [nginxwaf-0]: FAILED! => {"msg": "'nginx_app_protect_license' is undefined"}
```

nginx_app_protect_license is not described as a possible key/value in [main.yaml](https://github.com/nginxinc/ansible-role-nginx-app-protect/blob/main/defaults/main.yml)
but it is called [here](https://github.com/nginxinc/ansible-role-nginx-app-protect/blob/main/tasks/install/setup-license.yml#L17)

**To reproduce**
[playbook.yaml.TXT](https://github.com/nginxinc/ansible-role-nginx-app-protect/files/5592860/playbook.yaml.TXT)

**Expected behavior**
Doc: add nginx_app_protect_license key

**Your environment:**
-   Version of the NGINX App Protect role or specific commit: update collection before each job execution
-   Version of Ansible: 2.9.7
-   Target deployment platform: CentOS 7.4

**Comment by aknot242** [comment]
Fixed by PR #42 Resolved by introducing default dictionary values as the ansible-role-nginx role does.
